import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";
import ThemeContextProvider from "@/context/theme-provider";
import ActiveSectionContextProvider from "@/context/active-section";
import Header from "@/components/nav/Header";
import Footer from "@/components/nav/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ondřej Losenský",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-sora max-w-screen bg-shark-50 text-shark-950 dark:bg-shark-950 dark:text-shark-50  `}>
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <div className="min-h-screen flex flex-col justify-between w-[80%] mx-auto">
              <Header/>
              {children}
              <Footer/>
            </div>
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
